### ISSUE TITLE
Android Basics: dice-roller-images

### ISSUE THREAD

**Issue by Electron-Sanjay** [google-developer-training/android-basics-kotlin-dice-roller-with-images-app-solution#9] opened 2021-04-08 11:51 UTC
**URL of codelab**

https://developer.android.com/codelabs/basic-android-kotlin-training-dice-roller-images?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-four%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-dice-roller-images#3
**In which task and step of the codelab can this issue be found?**

**Describe the problem**

output as in code lab: dice image is not visible , it is visible only after we click roll button
actual output : dice image is visible as soon as we run the program

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by jhansitavva** [comment] 2021-06-21 23:06
@Electron-Sanjay 
Please provide us with the following details:
**In which task and step of the codelab can this issue be found?**

**Comment by osuleymanova** [comment] 2021-11-18 23:05
The issue is closed as no further clarification of it was provided.

**Closed as completed by osuleymanova** 2021-11-18 23:05 UTC
Labels: question
