### ISSUE TITLE
Android Basics: dice-roller-images

### ISSUE THREAD

**Issue by jayisreallycool** [google-developer-training/android-basics-kotlin-dice-roller-with-images-app-solution#8] opened 2021-04-08 01:40 UTC
**https://developer.android.com/codelabs/basic-android-kotlin-training-dice-roller-images?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-four%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-dice-roller-images#6**

**Solutions Portion of Codelab on GITBHUB**

**Compile error gives me crash on app start**

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by jhansitavva** [comment] 2021-06-21 23:04
@jayisreallycool 
Are you getting errors in the GitHub code?
If so please give screenshot and the copy paste the error message.

**Comment by osuleymanova** [comment] 2021-11-18 23:06
@jayisreallycool 
The issue is closed as no further clarification of it was provided.

**Closed as completed by osuleymanova** 2021-11-18 23:06 UTC
Labels: question
